### ISSUE TITLE
ModuleNotFoundError: No module named 'block.external'

### ISSUE THREAD

**Issue by ProbeTS** [yuleiniu/cfvqa#7]
Could you please tell me whether this error affects the experimental results?
```
[I 2021-10-12 03:55:06] ...trap/engines/engine.py.126: Saving best checkpoint for strategy eval_epoch.accuracy_top1
[I 2021-10-12 03:55:06] ...trap/engines/engine.py.420: Saving model...
Traceback (most recent call last):
  File "/data/gaokuofeng/anaconda3/envs/cfvqa/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/gaokuofeng/anaconda3/envs/cfvqa/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/gaokuofeng/anaconda3/envs/cfvqa/lib/python3.7/site-packages/block.bootstrap.pytorch-0.1.6-py3.7.egg/block/models/metrics/compute_oe_accuracy.py", line 8, in <module>
ModuleNotFoundError: No module named 'block.external'
[I 2021-10-12 03:55:07] ...trap/engines/engine.py.424: Saving optimizer...
[I 2021-10-12 03:55:10] ...trap/engines/engine.py.428: Saving engine...
[I 2021-10-12 03:55:10] ...trap/engines/engine.py.129: Saving last checkpoint
[I 2021-10-12 03:55:10] ...trap/engines/engine.py.420: Saving model...
[I 2021-10-12 03:55:11] ...trap/engines/engine.py.424: Saving optimizer...
[I 2021-10-12 03:55:14] ...trap/engines/engine.py.428: Saving engine...
[I 2021-10-12 03:55:14] ...trap/engines/engine.py.133: Ending training procedures
```

**Comment by ProbeTS** [comment]
I appreciate it a lot for your help. It works successfully.
